# Generated by Django 4.2.1 on 2023-05-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imgae',
            new_name='image',
        ),
    ]
